### PR TITLE
feat: add ED25519 support

### PR DESCRIPTION
**Pull request by nikolay**
Nowadays, most recommend using [Ed25519](https://ed25519.cr.yp.to/), so, this little PR adds support for it. Addresses https://github.com/hashicorp/terraform-provider-tls/issues/26 in part.

### CODE REVIEW

**Comment by jackivanov** [comment]
Isn't this already addressed in #59?

**Comment by nikolay** [comment]
@jackivanov That's pretty dated and needs more work.

**Comment by invidian** [comment]
@nikolay I'm happy to rebase #59. Why didn't you ping me? :)

**Comment by invidian** [comment]
@lagoda-antithesis my PR #59 seems to be using `ed25519.GenerateKey` the right way.

**Comment by nikolay** [comment]
@invidian The reason I created a new PR was that yours was based on an outdated base as far as I can recall and needed more rework than doing it from scratch. @lagoda-antithesis I am sorry about this - I will fix it. This should not be about ego (my PR vs your PR), but about finally having this basic feature cleanly into the codebase.

**Comment by invidian** [comment]
>@invidian The reason I created a new PR was that yours was based on an outdated base as far as I can recall and needed more rework than doing it from scratch.

Fair enough. I almost lost hope this ever get merged anyway, so whatever is easier for non-existing maintainers to grasp :)

**Comment by c33s** [comment]
@bflad just had a look who might have merge permissions in this repo and saw your username, may you be so kind and have a look at this merge request which would add ed25519 support. does hashicorp doesn't see this as security topic?

**Comment by nikolay** [comment]
@detro I did fix the obvious and pretty embarrassing for me issues. I need to see how to test this as `make test` does not work for me.

**Comment by detro** [comment]
Thank you for your time and contribution, we really appreciate it. As part of a bigger effort to add complete support for ED25519 key algorithm, I’m closing this in favor of issue [#150](https://github.com/hashicorp/terraform-provider-tls/issues/150). Please refer to the new issue for what will be included and how work will proceed.

**Pull request closed without merging**
